// angular-sample/src/app/sign-in/sign-in.component.ts
import { Component, Output, EventEmitter, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['../app.css', './sign-in.component.css'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SignIn {
  @Output() signIn = new EventEmitter<void>();
  @Input() isSigningIn: boolean = false;

  triggerSignIn() {
    this.signIn.emit();
  }
}

<div class="sign-in-content">
  <div class="sign-in-main">
    <img src="dragon-copilot.svg" class="sign-in-app-logo" />
    <label class="sign-in-app-title">Microsoft Dragon Copilot SDK for JavaScript Sample</label>
    <fluent-button (click)="triggerSignIn()" [disabled]="isSigningIn">Sign in</fluent-button>
  </div>
  <div class="microsoft-logo-wrapper">
    <img src="microsoft.svg" />
  </div>
</div>

// react-sample-with-dragon-copilot/src/components/sign-in/SignIn.tsx
import { useState } from "react";
import { useAuthContext } from "../../context/auth-context";
import "./SignIn.css";
import { Button } from "@fluentui/react-components";

export function SignIn() {
  const { authService } = useAuthContext();
  const [isLoading, setIsLoading] = useState(false);

  const signIn = async () => {
    setIsLoading(true);
    try {
      await authService.signinPopup();
      window.location.reload(); // Refresh to update auth state
    } catch (error) {
      console.error("Signin error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="sign-in-content">
      <div className="sign-in-main">
        <img src="/dragon-copilot.svg" className="sign-in-app-logo" />
        <label className="sign-in-app-title">Microsoft Dragon Copilot SDK for JavaScript Sample</label>
        <Button onClick={signIn} appearance="primary" disabled={isLoading} className="sign-in-button">
          Sign in
        </Button>
      </div>
      <div className="microsoft-logo-wrapper">
        <img src="/microsoft.svg" />
      </div>
    </div>
  );
}
